# NAme of the GitHub Actions workflow 
name: CI

# Controls when the workflow will run   
on: [push, pull_request]
  # Trigger the workflow only for push or PR to main 
  # branch 
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

jobs:
  ci:
    # Set up operating system
    runs-on: ubuntu-latest

    # Define job steps
    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Check-out repository
      uses: actions/checkout@v2

    - name: Install packages
      run: pip install -r REQUIREMENTS.txt

    - name: Test with pytest
      run: pytest tests/ --cov=dgufs --cov-report=xml

    - name: Use Codecov to track coverage
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.xml   # coverage report

    - name: Build documentation
      run: make html --directory docs/