# NAme of the GitHub Actions workflow 
name: CI

# Controls when the workflow will run 
on:
  # Trigger the workflow only for push or PR to main 
  # branch 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  # Enable running the workflow manually fro mthe Actions tab 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository so your job can access it
      - name: Check-out repository
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
