# NAme of the GitHub Actions workflow 
name: CI

# Controls when the workflow will run   
on: [push, pull_request]
  # Trigger the workflow only for push or PR to main 
  # branch 
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

jobs:
  ci:
    # Set up operating system
    runs-on: ubuntu-latest

    # Define job steps
    steps:
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
        #cache: 'pip'

    - name: Check-out repository
      uses: actions/checkout@v4

    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -r REQUIREMENTS.txt
        python -m pip install -e .

    - name: Test with pytest
      run: |
        pytest tests/ 

    #- name: Lint with Ruff
    #  run: |
    #    pip install ruff
    #    ruff --output-format=github .
    #  continue-on-error: true

    #- name: Use Codecov to track coverage
    #  uses: codecov/codecov-action@v2
    #  with:
    #    files: ./coverage.xml   # coverage report

    #- name: Build documentation
    #  run: make html --directory docs/